import pandas as pd
import streamlit as st
from pathlib import Path

st.set_page_config(
    page_title="Enterprise Reporting Dashboard",
    page_icon="📊",
    layout="wide"
)


BASE_DIR = Path(__file__).resolve().parents[2]
PROCESSED_DATA_PATH = BASE_DIR / "data" / "processed" / "Control_Reporting_Dataset.xlsx"
OUTPUT_DATA_PATH = BASE_DIR / "data" / "output"


@st.cache_data
def load_reporting_dataset(file_path: Path) -> pd.DataFrame:
    """Load the processed reporting dataset used by the dashboard."""
    return pd.read_excel(file_path)


st.title("Enterprise Reporting Automation Engine")
st.subheader("Interactive Executive Dashboard")

st.markdown(
    """
    This dashboard provides an interactive view of reporting outputs generated by the
    Enterprise Reporting Automation Engine.
    """
)

if not PROCESSED_DATA_PATH.exists():
    st.error(f"Processed dataset not found: {PROCESSED_DATA_PATH}")
    st.stop()

reporting_df = load_reporting_dataset(PROCESSED_DATA_PATH)

st.divider()

st.header("Executive KPI Summary")

total_records = len(reporting_df)

open_issues = (
    reporting_df["Issue Status"].eq("Open").sum()
    if "Issue Status" in reporting_df.columns
    else 0
)

closed_issues = (
    reporting_df["Issue Status"].eq("Closed").sum()
    if "Issue Status" in reporting_df.columns
    else 0
)

critical_items = (
    reporting_df["Severity"].eq("Critical").sum()
    if "Severity" in reporting_df.columns
    else 0
)

col1, col2, col3, col4 = st.columns(4)

col1.metric("Total Records", total_records)
col2.metric("Open Issues", open_issues)
col3.metric("Closed Issues", closed_issues)
col4.metric("Critical Items", critical_items)

st.divider()

st.header("Reporting Dataset Preview")

st.dataframe(reporting_df, use_container_width=True)

st.divider()

st.header("Available Report Outputs")

for report_file in [
    "Executive_Report.xlsx",
    "Exception_Report.xlsx",
    "Validation_Test_Results.xlsx",
]:
    report_path = OUTPUT_DATA_PATH / report_file

    if report_path.exists():
        with open(report_path, "rb") as file:
            st.download_button(
                label=f"Download {report_file}",
                data=file,
                file_name=report_file,
                mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
            )
    else:
        st.warning(f"{report_file} not found.")